version: '2'
services: 
  redis:
    image: redis
    ports: 
      - "6379:6379" 
  mongodb:
    image: mongo:3.2
    volumes: 
      - /data/db
    ports:
      - "27017:27017"
  influxdb:
    image: tutum/influxdb:latest
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    hostname: influxdb
    environment:
      PRE_CREATE_DB: 'polynect_stats'
  rabbitmq:
    image: rabbitmq:3.6.0-management
    ports:
      - "15672:15672"
      - "5672:5672"
    hostname: rabbitmq
