version: '2'
services: 
  web:
    image: node:7.2-alpine
    ports: 
      - "9999:9999"
    volumes: 
      - ./:/app
    environment:
      REDIS_URL: 'redis://redis:6379'
      POLYNECT_MONGO_URI: 'mongodb://mongodb:27017/polynect-test'
      AMQP_URL: 'amqp://rabbitmq'
    depends_on:
      - redis
      - mongodb
      #- influxdb
      - rabbitmq
    entrypoint: 'node app'
  redis:
    image: redis
    hostname: redis
    ports: 
      - "6379:6379"
      - "9539:9539"
  mongodb:
    image: mongo:3.2
    volumes: 
      - /data/db
    hostname: mongodb
    ports:
      - "27017:27017"
  influxdb:
    image: tutum/influxdb:latest
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    hostname: influxdb
    environment:
      PRE_CREATE_DB: 'polynect_stats'
  rabbitmq:
    # guest:guest
    image: rabbitmq:3.6.0-management
    ports:
      - "15672:15672"
      - "5672:5672"
    hostname: rabbitmq
  watch:
      image: node:7.2-alpine
      volumes:
      - .:/app
      entrypoint: 'npm --prefix app run watch'
